// One-off generator that ported the prototype's buildSeed() algorithm into fictitious example
// data. The app no longer reads this file directly (colaboradores now comes from Supabase, shared
// with Portal SST) — kept only to regenerate colaboradores.example.json if the reference shape
// needs to change.
import { writeFileSync } from "node:fs";

const RAW = [
  ["Cintia Santos Silva Batista", "Analista Administrativo", "Administrativo"],
  ["Miguel Cruz Cambeses", "Jovem Aprendiz", "Aprendiz"],
  ["Patricio Fe de Oliveira", "Analista Contábil", "Contabilidade"],
  ["Felipe Marcos Peixoto Pereira", "Assistente de Controle da Qualidade", "Controle da Qualidade"],
  ["Manuela Fraga Fernandes e Silva", "Assistente de Controle da Qualidade", "Controle da Qualidade"],
  ["Fabiana Santos Sousa", "Inspetora da Qualidade", "Controle da Qualidade"],
  ["Ravena Peixoto dos Santos", "Supervisora de Controle da Qualidade", "Controle da Qualidade"],
  ["Italo Rafael Araujo Zorzetto", "Analista de Engenharia", "Engenharia"],
  ["Lucas Prata Oliveira", "Analista de Engenharia", "Engenharia"],
  ["Rodrigo Araujo Porto Bomfim", "Analista de Engenharia", "Engenharia"],
  ["Rebeca Santos Souza Oliveira", "Analista de Melhoria Contínua", "Engenharia"],
  ["Elen Pereira Barboza Brandão", "Analista de Projetos de Engenharia", "Engenharia"],
  ["Victor Antunes Silva Barbosa", "Coordenador de Engenharia", "Engenharia"],
  ["Marcelo Ricardo Araújo Bacelar de Lima", "Estagiário (a)", "Engenharia"],
  ["Drielly Mitie Mizushima Victor", "Analista Financeiro", "Financeiro"],
  ["Ednalva Nascimento da Silva", "Assistente de Logística", "Logística"],
  ["Italo da Silva Figueiredo", "Assistente de Logística", "Logística"],
  ["Leandro de Jesus Silva", "Assistente de Logística", "Logística"],
  ["Mirailton de Santana Santana", "Assistente de Logística", "Logística"],
  ["Iago Rosas Iung", "Líder de Manutenção", "Manutenção"],
  ["Jaqueline Lima Teixeira", "Assistente de Operações de Vendas", "Operações de Vendas"],
  ["Luciana Kelly Rocha Santos", "Assistente de Operações de Vendas", "Operações de Vendas"],
  ["Selma Ribeiro Bispo", "Supervisor(a) de Operação de Vendas", "Operações de Vendas"],
  ["Maria Lívia de Oliveira Ferreira", "Analista de Planejamento", "PCP e Compras"],
  ["Lucas Pugliesi Di Girolamo", "Assistente de Planejamento", "PCP e Compras"],
  ["Alice Coutinho da Cruz", "Auxiliar de Produção I", "Produção"],
  ["Ana Beatriz Souza Figueiredo", "Auxiliar de Produção I", "Produção"],
  ["Bruna Fernanda dos Santos Silva", "Auxiliar de Produção I", "Produção"],
  ["Bruna Santos Nascimento", "Auxiliar de Produção I", "Produção"],
  ["Leildes de Queiros Bonfim", "Auxiliar de Produção I", "Produção"],
  ["Poliana Aline de Cerqueira Vieira", "Auxiliar de Produção I", "Produção"],
  ["Silvana Trindade Pires dos Santos", "Auxiliar de Produção I", "Produção"],
  ["Taísa Trindade da Cruz", "Auxiliar de Produção I", "Produção"],
  ["Yasmin Batista Santos", "Auxiliar de Produção I", "Produção"],
  ["Ana Maria Alves Santos", "Auxiliar de Produção II", "Produção"],
  ["Edilcelia Souza de Jesus", "Auxiliar de Produção III", "Produção"],
  ["Janete Carvalho de Jesus", "Auxiliar de Produção III", "Produção"],
  ["Joice Melo dos Santos", "Auxiliar de Produção III", "Produção"],
  ["Tainara Correia dos Santos", "Supervisora de Produção", "Produção"],
  ["Mateus Chaves Moura", "Assistente de T.I", "Projetos e TI"],
  ["Juliana Ranzan Matos", "Analista da Qualidade e Assuntos Regulatórios", "Qualidade e Regulatório"],
  ["Cidália Pereira Cardoso", "Auxiliar de Serviços Gerais", "Qualidade e Regulatório"],
  ["Tais Batista Santos Araújo", "Auxiliar de Serviços Gerais", "Qualidade e Regulatório"],
  ["William Alves Cruz", "Auxiliar de Serviços Gerais", "Qualidade e Regulatório"],
  ["Raissa Rayane Santos Laurindo Caldas", "Coordenador(a) da Garantia da Qualidade", "Qualidade e Regulatório"],
  ["Carolina Matos da Cruz", "Analista de RH", "Recursos Humanos"],
  ["Leslie Silva Souza", "Assistente de Gente e Gestão", "Recursos Humanos"],
  ["Manuele Rodrigues dos Santos", "Jovem Aprendiz", "Aprendiz"],
  ["Davi Cunha Barbosa Moreira", "Técnico de Manutenção", "Manutenção"],
  ["Tassio Antonio Lima Sant Ana", "Gerente Industrial", "Industrial e Diretoria"],
  ["Yuri Ivonei Crispim", "Diretor Industrial", "Industrial e Diretoria"],
  ["Daniel Emiliano Suguer", "CEO", "Industrial e Diretoria"],
  ["Ana Lucia Noto", "Consultor(a) Comercial", "Comercial"],
  ["Cristiane Andrade", "Key Account Manager", "Comercial"],
  ["Laisa Rocha Ferreira Machado dos Santos", "Key Account Manager", "Comercial"],
];

const CODE = {
  Administrativo: "ADM", Aprendiz: "APR", Contabilidade: "CTB", "Controle da Qualidade": "CQ",
  Engenharia: "ENG", Financeiro: "FIN", Logística: "LOG", Manutenção: "MNT",
  "Operações de Vendas": "OPV", "PCP e Compras": "PCP", Produção: "PRD", "Projetos e TI": "TI",
  "Qualidade e Regulatório": "QR", "Recursos Humanos": "RH", "Industrial e Diretoria": "DIR", Comercial: "COM",
};

const GESTOR = {
  "Cintia Santos Silva Batista": "Daniel Emiliano Suguer",
  "Miguel Cruz Cambeses": "Tassio Antonio Lima Sant Ana",
  "Patricio Fe de Oliveira": "Daiana Leite",
  "Felipe Marcos Peixoto Pereira": "Ravena Peixoto dos Santos",
  "Manuela Fraga Fernandes e Silva": "Ravena Peixoto dos Santos",
  "Fabiana Santos Sousa": "Ravena Peixoto dos Santos",
  "Ravena Peixoto dos Santos": "Tassio Antonio Lima Sant Ana",
  "Italo Rafael Araujo Zorzetto": "Victor Antunes Silva Barbosa",
  "Lucas Prata Oliveira": "Victor Antunes Silva Barbosa",
  "Rodrigo Araujo Porto Bomfim": "Victor Antunes Silva Barbosa",
  "Rebeca Santos Souza Oliveira": "Victor Antunes Silva Barbosa",
  "Elen Pereira Barboza Brandão": "Victor Antunes Silva Barbosa",
  "Victor Antunes Silva Barbosa": "Yuri Ivonei Crispim",
  "Marcelo Ricardo Araújo Bacelar de Lima": "Victor Antunes Silva Barbosa",
  "Drielly Mitie Mizushima Victor": "Pedro Henrique Lages Rocha",
  "Ednalva Nascimento da Silva": "Tassio Antonio Lima Sant Ana",
  "Italo da Silva Figueiredo": "Tassio Antonio Lima Sant Ana",
  "Leandro de Jesus Silva": "Tassio Antonio Lima Sant Ana",
  "Mirailton de Santana Santana": "Tassio Antonio Lima Sant Ana",
  "Iago Rosas Iung": "Tassio Antonio Lima Sant Ana",
  "Jaqueline Lima Teixeira": "Selma Ribeiro Bispo",
  "Luciana Kelly Rocha Santos": "Selma Ribeiro Bispo",
  "Selma Ribeiro Bispo": "Daniel Emiliano Suguer",
  "Maria Lívia de Oliveira Ferreira": "Tassio Antonio Lima Sant Ana",
  "Lucas Pugliesi Di Girolamo": "Tassio Antonio Lima Sant Ana",
  "Alice Coutinho da Cruz": "Tainara Correia dos Santos",
  "Ana Beatriz Souza Figueiredo": "Tainara Correia dos Santos",
  "Bruna Fernanda dos Santos Silva": "Tainara Correia dos Santos",
  "Bruna Santos Nascimento": "Tainara Correia dos Santos",
  "Leildes de Queiros Bonfim": "Tainara Correia dos Santos",
  "Poliana Aline de Cerqueira Vieira": "Tainara Correia dos Santos",
  "Silvana Trindade Pires dos Santos": "Tainara Correia dos Santos",
  "Taísa Trindade da Cruz": "Tainara Correia dos Santos",
  "Yasmin Batista Santos": "Tainara Correia dos Santos",
  "Ana Maria Alves Santos": "Tainara Correia dos Santos",
  "Edilcelia Souza de Jesus": "Tainara Correia dos Santos",
  "Janete Carvalho de Jesus": "Tainara Correia dos Santos",
  "Joice Melo dos Santos": "Tainara Correia dos Santos",
  "Tainara Correia dos Santos": "Tassio Antonio Lima Sant Ana",
  "Mateus Chaves Moura": "Yuri Ivonei Crispim",
  "Juliana Ranzan Matos": "Raissa Rayane Santos Laurindo Caldas",
  "Cidália Pereira Cardoso": "Raissa Rayane Santos Laurindo Caldas",
  "Tais Batista Santos Araújo": "Raissa Rayane Santos Laurindo Caldas",
  "William Alves Cruz": "Raissa Rayane Santos Laurindo Caldas",
  "Raissa Rayane Santos Laurindo Caldas": "Yuri Ivonei Crispim",
  "Carolina Matos da Cruz": "Yuri Ivonei Crispim",
  "Leslie Silva Souza": "Carolina Matos da Cruz",
  "Manuele Rodrigues dos Santos": "Cintia Santos Silva Batista",
  "Davi Cunha Barbosa Moreira": "Iago Rosas Iung",
  "Tassio Antonio Lima Sant Ana": "Yuri Ivonei Crispim",
  "Yuri Ivonei Crispim": "Daniel Emiliano Suguer",
  "Daniel Emiliano Suguer": "Bernardo Machado",
  "Ana Lucia Noto": "Daniel Emiliano Suguer",
  "Cristiane Andrade": "Daniel Emiliano Suguer",
  "Laisa Rocha Ferreira Machado dos Santos": "Daniel Emiliano Suguer",
};

const NIVEL = {
  CEO: "Diretoria", "Diretor Industrial": "Diretoria", "Gerente Industrial": "Gerência",
  "Coordenador de Engenharia": "Liderança", "Coordenador(a) da Garantia da Qualidade": "Liderança",
  "Supervisora de Controle da Qualidade": "Liderança", "Supervisor(a) de Operação de Vendas": "Liderança",
  "Supervisora de Produção": "Liderança", "Líder de Manutenção": "Liderança",
  "Analista Administrativo": "Analista", "Analista Contábil": "Analista", "Analista de Engenharia": "Analista",
  "Analista de Melhoria Contínua": "Analista", "Analista de Projetos de Engenharia": "Analista",
  "Analista Financeiro": "Analista", "Analista de Planejamento": "Analista",
  "Analista da Qualidade e Assuntos Regulatórios": "Analista", "Analista de RH": "Analista",
  "Inspetora da Qualidade": "Técnico", "Técnico de Manutenção": "Técnico", "Assistente de T.I": "Técnico",
  "Key Account Manager": "Especialista", "Consultor(a) Comercial": "Especialista",
  "Jovem Aprendiz": "Aprendiz / Estágio", "Estagiário (a)": "Aprendiz / Estágio",
};

const months = ["jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez"];

const colaboradores = RAW.map((t, i) => {
  const [nome, cargo, depto] = t;
  const yr = 2019 + (i % 7);
  const mo = (i * 5) % 12;
  const dy = ((i * 7) % 27) + 1;
  return {
    vinculo: "CLT",
    nome, cargo, depto,
    deptoCode: CODE[depto],
    nivel: NIVEL[cargo] || "Operacional",
    gestor: GESTOR[nome] || "—",
    admissao: String(dy).padStart(2, "0") + "/" + months[mo] + "/" + yr,
  };
});

writeFileSync(new URL("../src/data/colaboradores.example.json", import.meta.url), JSON.stringify(colaboradores, null, 2));
console.log("Generated", colaboradores.length, "colaboradores (fictitious example data)");
